<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="0.137">
	<testcase classname="tests.test_simple_mapping.TestSimpleMapping" file="tests\test_simple_mapping.py" line="4" name="test_map1" time="0.001001119613647461">
		<properties>
			<property name="id" value="4"/>
		</properties>
		<system-out>Map 1
		</system-out>
	</testcase>
	<testcase classname="tests.test_simple_mapping.TestSimpleMapping" file="tests\test_simple_mapping.py" line="8" name="test_map2" time="0.003003358840942383">
		<properties>
			<property name="id" value="5"/>
		</properties>
		<system-out>Map 2
		</system-out>
	</testcase>
	<testcase classname="tests.test_simple_mapping.TestSimpleMapping" file="tests\test_simple_mapping.py" line="12" name="test_map3" time="0.014985799789428711">
		<properties>
			<property name="id" value="6"/>
		</properties>
		<failure message="assert False">self = &lt;test_simple_mapping.TestSimpleMapping object at 0x000001DD2A6C6898&gt;

    @pytest.mark.ext_link(id=6)
    def test_map3(self):
        print(&quot;Map 3&quot;)
&gt;       assert False
E       assert False

tests\test_simple_mapping.py:16: AssertionError</failure>
		<system-out>Map 3
		</system-out>
	</testcase>
</testsuite>